### ISSUE TITLE
Exception when Connecting to BAS Landscape

### ISSUE THREAD

**Issue by jung-thomas** [SAP/app-studio-toolkit#229]
When I try and connect to the BAS Landscape I get the following excpetion:
![image](https://user-images.githubusercontent.com/12159356/235455344-3e7f84f5-5834-4cf8-b7ee-9b240da7315f.png)

**Comment by alex-gilin** [comment]
The issue is solved by https://github.com/SAP/app-studio-toolkit/pull/228 and will be available in the next release.

**Comment by alex-gilin** [comment]
v1.13.2 released
