### ISSUE TITLE
Cannot activate the 'SAP Business Application Studio toolkit' extension because it depends on the 'Remote - SSH: Editing Configuration Files' extension, which is not loaded

### ISSUE THREAD

**Issue by szalayak** [SAP/app-studio-toolkit#253]
When I use VSCode under WSL (Windows Subsystem for Linux), I get this error whenever I start VS Code. I also can't use the Fiori Application Generator, it just doesn't start. Guided development works normally. I don't get this error if I open VSCode under Windows, only when logged in to the local WSL environment.

`Cannot activate the 'SAP Business Application Studio toolkit' extension because it depends on the 'Remote - SSH: Editing Configuration Files' extension, which is not loaded. Would you like to reload the window to load the extension?`

<img width="352" alt="image" src="https://github.com/SAP/app-studio-toolkit/assets/1292745/c2ae3581-67d0-4c19-927d-e0048224fe52">

I checked and the extension is enabled globally

![image](https://github.com/SAP/app-studio-toolkit/assets/1292745/e36f6210-9f17-4861-9ca2-b0f8cb93be84)

**Comment by ThePlenkov** [comment]
I have exactly same message. Very annoying.  Moreover - I totally don't understand - how did I manage to end up with SSH just by activating Fiori extension pack . What My proposal is - it should not be a hard dependency for application wizard to this extension - because most likely we develop apps locally exactly because we don't want to use BAS and that's how this extension is not really relevant for locahost scenario

**Comment by szalayak** [comment]
Yeah, this is a hard dependency for the Fiori Application Generator as well, which is currently broken on WSL. I wouldn't want to use the SAP BAS Toolkit on WSL, as if I do want to connect to BAS I'll do it from Windows as there's no benefit to using WSL, because the runtime will be BAS (Linux) anyway. Whereas for normal VS Code development there's a massive performance benefit with BAS. But yes, I don't want to use BAS, I would like to use VS Code, but this makes it more annoying and requires extra steps to make it work.

**Comment by rimasirich** [comment]
@szalayak @ThePlenkov An updated version of app-studio-toolkit with the fix for this issue was uploaded today to the marketplace.

**Comment by szalayak** [comment]
great, thanks!
