### ISSUE TITLE
Extension doesn't work in Linux/WSL

### ISSUE THREAD

**Issue by ThePlenkov** [SAP/app-studio-toolkit#292]
Hi! 

I try to use this extension.  So far my observation is - it's not working from WSL/Linux. It's only working from Windows host OS.

There are no logs in the output showing the issue.

Could you please check that?

Thank you!

**Comment by idoprz** [comment]
Hi,

You are right, but it's not an issue. BAS remote only works on the host machine (Windows/Mac/Linux), but will not work from a remote machine like WSL, remote container, etc;
