### ISSUE TITLE
Missing explicit dependency definition to the toolkit extension?

### ISSUE THREAD

**Issue by qmacro** [SAP/app-studio-toolkit#295]
There is a documentation page linked from the extension details page in VS Code, once installed: 

_"Remotely connect to SAP Business Application Studio dev spaces directly from a local Visual Studio Code desktop application. See [Access SAP Business Application Studio from VS Code](https://help.sap.com/docs/bas/sap-business-application-studio/working-remotely)."_

The "Prerequisites" section on this page indirectly mentions the [SAP Business Application Studio toolkit](https://marketplace.visualstudio.com/items?itemName=SAPOSS.app-studio-toolkit) extension: "_To ensure the best functionality, make sure you are always working (locally) on the latest officially released version of VS Code and that you regularly update the SAP Business Application Studio toolkit extension to the latest version._" but there is no link to it on the marketplace, which means users may miss this.

In addition, the "Dependencies" tab for the extension does not list the toolkit extension, just the "Remote - SSH" extension:

![image](https://github.com/SAP/app-studio-toolkit/assets/73068/49125dd5-3a4b-4b1a-8362-c855ae8778e5)

All this adds up to a slightly confusing experience, in that after installing this "Remote Access for SAP Business Application Studio" extension, nothing works, there is not even the SAP Business Application Studio view icon as described in the [Getting Started](https://help.sap.com/docs/bas/sap-business-application-studio/working-remotely?version=Cloud) section.

**Comment by Paolaufer** [comment]
Hi DJ,
Thank you for your feedback.
If I change the extension in the Getting Started section from the "Remote Access" one to the "SAP BAS Toolkit" one, would that solve the problem?

**Comment by qmacro** [comment]
Hey @Paolaufer ! Great to connect with you again! 

I think changing the documentation would be definitely something we should do, but I'm not sure that is everything, i.e. what about the missing entry in the "Dependencies" definition (screenshot above)?

**Comment by alex-gilin** [comment]
Hello @qmacro .
 Dependency information that the Code shows you in the `Extension: *` status editor, is generated automatically based on the extension's metadata. There is no direct runtime dependency of remote access extension to the toolkit extension pack, so this information is correct (conversely, the toolkit extension depends on remote access one to provide remote access to the development space).
Therefore, I think there is nothing to change here and the data displayed is correct.
Since the documentation page is updated I close the issue.
BR, AG

**Comment by qmacro** [comment]
I'm not sure I follow here, @alex-gilin . If you follow the VS Code path, find the Remote Access for SAP Business Application Studio extension, read the info, you would think "great, that's what I need!" and install it. 

But then you'd be frustrated, as at this point nothing works. There's no Business Application Studio view to even start from.

The documentation (in the Help Portal) mentions the toolkit is a prerequisite. Even the details for the SAP Business Application Studio toolkit extension says "This toolkit is a prerequisite for other extensions that require its SAP capabilities." Now I am not sure there is any subtle contrast between the words "dependency" and "prerequisite" here that make any difference ... so surely it makes sense to specify the SAP Business Application Studio toolkit as a dependency in the metadata, for two reasons:

- so that the user is not confused and frustrated when they install the Remote Access for SAP Business Application Studio extension and nothing works
- to be consistent between the documentation, the requirements, and the extension metadata

To require the user to have to read the Details text of the Remote Access for SAP Business Application Studio extension, *and* follow the link (which is just there as a courtesy), *and* read all the documentation, just to find out how to get the extension to actually work, doesn't seem ideal to me. How many other extensions in VS Code require this level of perseverence, persistence and avid documentation consumption to go from "find" - "select" - "install" - "use"?

**Comment by Paolaufer** [comment]
Hi @qmacro ,
We added a clearer prerequisite with a link to the toolkit extension.
I will also make sure the documentation is not vague about this extension being a prerequisite.
