### ISSUE TITLE
Where is the BAS button in VS Code?

### ISSUE THREAD

**Issue by ThePlenkov** [SAP/app-studio-toolkit#351]
Hi! I have the extension installed , but the button hasn't appeared on the left in a toolbar and is not also hidden - it's just not there in a list. Why?

![Image](https://github.com/user-attachments/assets/3894d6b9-7862-40f8-b109-5cb72aa8988b)
![Image](https://github.com/user-attachments/assets/1f3751d4-a1bb-443b-a0e1-0cb4d789aa9a)

**Comment by ThePlenkov** [comment]
Funny, I don't remember it - but seems like I already reported similar issue before: #292 . I guess it doesn't work in WSL/Linux

**Comment by idoprz** [comment]
Hi,

You are right, but it's not an issue. BAS remote only works on the host machine (Windows/Mac/Linux), but will not work from a remote machine like WSL, remote container, etc;

**Comment by ThePlenkov** [comment]
@idoprz may I ask why is like this? I'm very curious - is it done intentionally - or because of some limitation? Thanks!

I think we're significantly reducing the circle of devs potentially interested in using BAS.  In my case I'd prefer even not to use it locally if it requires Windows. WSL - is not event the target. Devcontainer is the actual target where I'd like BAS extension to be used.

**Comment by ThePlenkov** [comment]
There is a reason why such a thing as https://containers.dev/ was introduced. Working in a container helps us to set up any environment and be 100% sure it is identical regardless when it runs - on Windows, Linux or Mac. Inside we have some base image + installed libraries. With web containers https://webcontainers.io/ it becomes even more achievable. So talking about tools like CAP - it becomes very easy to pick up NodeJS or Java container and open the project there instead of setting up the environment. 
Moreover talking about Windows - unfortunately there are plenty of tools which don't really work in Windows nicely ( like scripts only support Linux ). Additionally even mounting Windows folder to a WSL/Linux webcontainer - there is NTFS file ssytem behind and commands like `npm install` or commands like `watch` work much worse from persepctive of performnance rather than with Linux native ext4 format. 

So that's why not all devs are ready to start working in Windows only because of that. 

I'm not that big expert in VS Code Remote functionality , so for sure you know better what to do . But I just feel like there must be a way to solve this problem by connecting to a remote environment from VS Code , from WSL or devcontainer.

I'm just curious - can't may be remote tunnels help? 

https://code.visualstudio.com/docs/remote/tunnels

According to what they state here it could be possible:
https://code.visualstudio.com/docs/remote/tunnels#_can-i-use-other-remote-development-extensions-or-a-dev-container-while-im-tunneling

So probably if BAS server would have a remote tunnel server - it will be possible to connect to it from a local environment, it doesn't matter OS, WSL or container.  But i'm not 100%b sure about this..

**Comment by idoprz** [comment]
Hi @ThePlenkov 

The BAS remote extension is exactly what you are describing here. You work remotely from the host machine on the remote target which is BAS in this case. This is very similar to working with Dev containers, but this containers are remote machines managed by BAS. If your host machine is Windows/Mac/Linux it does not matter, as the dev environment is running remotely - linux in BAS case. So the drawbacks you describe for working in Windows are not relevant as you are working on the remote machine - Linux.

So your last state is 100% correct, and the remote extension for BAS does exactly that - it tunnels from your host environment to BAS. [https://marketplace.visualstudio.com/items?itemName=SAPOSS.app-studio-remote-access](https://marketplace.visualstudio.com/items?itemName=SAPOSS.app-studio-remote-access)

**Comment by ThePlenkov** [comment]
Ok, but if VS Code allows remote tunnels from WSL/Devcontainers - why BAS extension doesn't support this. 

You referenced to Remote - SSH extension (https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-ssh-edit) 

And I mean Remote - Tunnels : https://marketplace.visualstudio.com/items?itemName=ms-vscode.remote-server

If first one will probably indeed will not work from WSL/Devcontainer because it's already remote - the scenond one should work according to docs.

So what BAS uses to connect - SSH or remote tunnels? 

Thanks!

**Comment by idoprz** [comment]
The remote tunnel extension requires you to have VSCode on the host machine (full blown VSCode or just the CLI) - see "Make a tunnel available" section in the extension readme.
We cannot deliver VSCode product as part of BAS. Also the tunnel extension does not manage the lifecycle of the remote machine. Also, you would need to use github service (which is Microsoft product) to register your remote machine IP. Many of our customers would not like to have their users login to a Microsoft product.
So, technically you can install it yourself but I believe the user experience will not be so great and you might violate your corporate guidelines. You would need to start the DevSpace every time from the browser and start the VSCode process on the remote machine.

BAS is using remote SSH with Microsoft dev tunnels (https://github.com/microsoft/dev-tunnels) which is the infrastructure of the remote tunnels extension. It uses SSH over WebSocket connection because SSH is often blocked by corporate firewalls.
